server:
  port:  8763
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://zolmk:zolmk@eureka-node-a:8761/eureka/,http://zolmk:zolmk@eureka-node-b:8762/eureka/
    instance:
      hostname: eureka-node-c
      prefer-ip-address: false