server:
  port:  8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://zolmk:zolmk@eureka-node-a:8761/eureka/,http://zolmk:zolmk@eureka-node-c:8763/eureka/
    instance:
      hostname: eureka-node-b
      prefer-ip-address: false