server:
  port: 8888

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/helloadg/spring-cloud-config.git
          basedir: target/config
          default-label: main
          username: helloadg
          password: zhenlu8875

---
spring:
  config:
    activate:
      on-profile: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://zolmk:zolmk@eureka-node-b:8762/eureka/,http://zolmk:zolmk@eureka-node-c:8763/eureka/,http://zolmk:zolmk@eureka-node-a:8761/eureka/
  instance:
    instance-id: config-server
    refer-ip-address: true