spring:
  application:
    name: study-admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #这个是你server.properties中配置的
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group #这个去config/consumer.properties中查看和修改 # 不过好像不一样也不影响？
      bootstrap-servers: localhost:9092
server:
  port: 8001
eureka:
  instance:
    appname: study-admin
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://zolmk:zolmk@eureka-node-b:8762/eureka/,http://zolmk:zolmk@eureka-node-c:8763/eureka/,http://zolmk:zolmk@eureka-node-a:8761/eureka/
