spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9100
  servlet:
    context-path: /

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://zolmk:zolmk@eureka-node-b:8762/eureka/,http://zolmk:zolmk@eureka-node-c:8763/eureka/,http://zolmk:zolmk@eureka-node-a:8761/eureka/
  instance:
    appname: gateway-server
    prefer-ip-address: true
